package ru.mai.k806.Letters;

import ru.mai.k806.Examples.Letters.LetterInput;
import ru.mai.k806.commons.*;
import ru.mai.k806.commons.SOFM;
import ru.mai.k806.commons.Sample;

import javax.swing.*;
import java.util.LinkedList;
import java.util.List;

�����������������������_0;

/**
 * @author Andrew
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        letterInputA1.setImageEditable(false);
        letterInputB1.setImageEditable(false);
        letterInputC1.setImageEditable(false);
        letterInputA2.setImageEditable(false);
        letterInputB2.setImageEditable(false);
        letterInputC2.setImageEditable(false);
        letterInputA3.setImageEditable(false);
        letterInputB3.setImageEditable(false);
        letterInputC3.setImageEditable(false);

        letterUserInput.setImageEditable(true);

        jPanel1.add(letterInputA1);
        jPanel1.add(letterInputB1);
        jPanel1.add(letterInputC1);

        jPanel2.add(letterInputA2);
        jPanel2.add(letterInputB2);
        jPanel2.add(letterInputC2);

        jPanel4.add(letterInputA3);
        jPanel4.add(letterInputB3);
        jPanel4.add(letterInputC3);

        jPanel3.add(letterUserInput);
        letterUserInput.setBounds(0, 0, jPanel3.getWidth(), jPanel3.getHeight());
        //jPanel3.getGraphics().fillRect(0,0,10,10);
    }

    //0
    private LetterInput letterInputA1 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 1, 1, 1}
    });
    //1
    private LetterInput letterInputB1 = new LetterInput(new int[][]{
            {0, 0, 1, 0},
            {0, 1, 1, 0},
            {1, 1, 1, 0},
            {0, 0, 1, 0},
            {0, 0, 1, 0},
            {0, 1, 1, 1}
    });
    //2
    private LetterInput letterInputC1 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {0, 0, 0, 1},
            {0, 0, 1, 0},
            {0, 1, 0, 0},
            {1, 0, 0, 0},
            {1, 1, 1, 1}
    });
    //0
    private LetterInput letterInputA2 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 1, 1, 1}
    });
    //1
    private LetterInput letterInputB2 = new LetterInput(new int[][]{
            {0, 0, 1, 0},
            {0, 1, 1, 0},
            {1, 1, 1, 0},
            {0, 0, 1, 0},
            {0, 0, 1, 0},
            {0, 1, 1, 1}
    });
    //2
    private LetterInput letterInputC2 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {0, 0, 0, 1},
            {0, 0, 1, 0},
            {0, 1, 0, 0},
            {1, 0, 0, 0},
            {1, 1, 1, 1}
    });
    //0
    private LetterInput letterInputA3 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 0, 0, 1},
            {1, 1, 1, 1}
    });
    //1
    private LetterInput letterInputB3 = new LetterInput(new int[][]{
            {0, 0, 1, 0},
            {0, 1, 1, 0},
            {1, 1, 1, 0},
            {0, 0, 1, 0},
            {0, 0, 1, 0},
            {0, 1, 1, 1}
    });
    //2
    private LetterInput letterInputC3 = new LetterInput(new int[][]{
            {1, 1, 1, 1},
            {0, 0, 0, 1},
            {0, 0, 1, 0},
            {0, 1, 0, 0},
            {1, 0, 0, 0},
            {1, 1, 1, 1}
    });


    private LetterInput letterUserInput = new LetterInput(4, 6);

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("\u041f\u043e\u043a\u0430 \u043d\u0435 \u0431\u0443\u0434\u0435\u0442 95% \u043f\u043e\u043f\u0430\u0434\u0430\u043d\u0438\u044f (<100 \u043f\u043e\u043f\u044b\u0442\u043e\u043a)");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("\u0421 \u043e\u0434\u043d\u043e\u0439 \u043f\u043e\u043f\u044b\u0442\u043a\u0438");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        jPanel3.setLayout(null);

        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));

        jButton1.setText("\u041f\u0443\u0441\u043a!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("\u0425\u043e\u0442\u0438\u0442\u0435 \u044f \u0434\u043e\u0433\u0430\u0434\u0430\u044e\u0441\u044c, \u0447\u0442\u043e \u0432\u044b \u0442\u0443\u0442 \u043d\u0430\u0440\u0438\u0441\u043e\u0432\u0430\u043b\u0438?");

        jCheckBox1.setText("\u0420\u0430\u0437\u0440\u0435\u0448\u0438\u0442\u044c \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u0440\u0430\u0437\u0446\u043e\u0432");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        saveButton.setText("\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("\u041d\u0430\u0431\u043e\u0440 N1"));
        jPanel5.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("\u041d\u0430\u0431\u043e\u0440 N2"));
        jPanel5.add(jPanel2);

        jPanel4.setLayout(new java.awt.GridLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("\u041d\u0430\u0431\u043e\u0440 N3"));
        jPanel5.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                                        .addComponent(loadButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                                        .addComponent(jCheckBox1)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBox1)
                                                .addGap(14, 14, 14)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(loadButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(saveButton))
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        letterInputA1.setImageEditable(jCheckBox1.isSelected());
        letterInputB1.setImageEditable(jCheckBox1.isSelected());
        letterInputC1.setImageEditable(jCheckBox1.isSelected());

        letterInputA2.setImageEditable(jCheckBox1.isSelected());
        letterInputB2.setImageEditable(jCheckBox1.isSelected());
        letterInputC2.setImageEditable(jCheckBox1.isSelected());

        letterInputA3.setImageEditable(jCheckBox1.isSelected());
        letterInputB3.setImageEditable(jCheckBox1.isSelected());
        letterInputC3.setImageEditable(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Sample> samples = new LinkedList<Sample>();
        samples.add(new Sample(letterInputA1.getLinearizedContent(), new double[]{1, 0, 0}));
        samples.add(new Sample(letterInputB1.getLinearizedContent(), new double[]{0, 1, 0}));
        samples.add(new Sample(letterInputC1.getLinearizedContent(), new double[]{0, 0, 1}));

        samples.add(new Sample(letterInputA2.getLinearizedContent(), new double[]{1, 0, 0}));
        samples.add(new Sample(letterInputB2.getLinearizedContent(), new double[]{0, 1, 0}));
        samples.add(new Sample(letterInputC2.getLinearizedContent(), new double[]{0, 0, 1}));

        samples.add(new Sample(letterInputA3.getLinearizedContent(), new double[]{1, 0, 0}));
        samples.add(new Sample(letterInputB3.getLinearizedContent(), new double[]{0, 1, 0}));
        samples.add(new Sample(letterInputC3.getLinearizedContent(), new double[]{0, 0, 1}));
        int index = (int) new SOFM(samples, 3).whatIsIt(letterUserInput.getLinearizedContent());
        if (index < 0)
            JOptionPane.showMessageDialog(this, "���� �� ����, ��� �� ������ �����..");
        else
            JOptionPane.showMessageDialog(this, "��� ������� ����� �� ������� N" + (index + 1));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
